apiVersion: v1
kind: Service 
metadata:
  name: replicaset-lb
  labels:
    app: myapp
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: myapp
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port #checkk
